server:
  servlet:
    context-path: /bser
  port: 11001

redcap:
  api:
    token: 1B0C7E1F7B2F4E2F7245E500D98D04E3
    url: https://redcap-azure-stage.ymca.net/api/


BSER_SENDER:
  #URL: https://webhook.site/063a021f-efad-4514-af8a-1803f5052f1c
  URL: http://69.8.221.121:19445